In [1]:
# syntax error prin
print("linear regression is a supervised learning algorithm")

linear regression is a supervised learning algorithm


In [2]:
# Runtime error. list index out of range with 5
numbers = list(range(5))
numbers[4]

4

In [3]:
# Install numpy. uv pip install numpy
import numpy as np

radius = 5
area_circle = np.pi * radius**2
print(f"{area_circle = :.2f}")

area_circle = 78.54


In [4]:
while True:
    try:
        age = float(input("Ange din ålder: "))
        if not 0<=age<=125:
            raise ValueError("Ålder måste vara mellan 0 och 125")
        print(f"Du är {age} år gammal")
        break
    except ValueError as err:
        print(err)

Du är 12.0 år gammal


In [5]:
def squarer(x):
    return x**2

print(squarer(3)) 
squares = [squarer(x) for x in range(10)] # 0-9
print(squares)

9
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [6]:
def smallest(number1, number2): #funktion
    if number1 > number2:
        return number2
    
smallest(7, 2)

2

In [7]:
def draw_ascii_pattern(number_rows=5):
    for i in range(1, number_rows + 1):
        print(i * "x " + (number_rows - i) *"o ")
        
draw_ascii_pattern()
draw_ascii_pattern(2)
draw_ascii_pattern(4)

x o o o o 
x x o o o 
x x x o o 
x x x x o 
x x x x x 
x o 
x x 
x o o o 
x x o o 
x x x o 
x x x x 


In [8]:
# args* = tuple
def my_mean(*args):
    sum_ = 0 #not overwrite sum() function
    for arg in args:
        sum_ += arg
    return sum_/len(args)
    
print(my_mean(1, 2, 3, 4))

2.5


In [9]:
import numpy as np

def simulate_dices(throws = 1, dices = 2):
    print(np.random.randint(1,7, (throws, dices)))

simulate_dices(throws = 2)

print("\ncan specify second keyword argument as long as first has default value")
simulate_dices(dices = 3)

print("\ndifferent orders")
simulate_dices(dices=3, throws=3)

[[4 2]
 [6 5]]

can specify second keyword argument as long as first has default value
[[2 1 2]]

different orders
[[3 1 3]
 [5 6 3]
 [5 3 3]]
